spring:
  application:
    name: shows

info:
  name: ${spring.application.name}
  version: ${version}

server:
  port: 8011

endpoints:
  shutdown:
    sensitive: false
    enabled: true
  health:
    sensitive: false